from pathlib import Path
p=Path('/mnt/data/round51_work')

# --- Analytics hardening ---
mp=p/'mastery_services.py'
s=mp.read_text()
needle="def assign_experiment(conn, *, experiment_key: str, subject_key: str) -> str | None:\n"
insert='''def ensure_experiment_mastery_schema(conn):\n    conn.execute("""CREATE TABLE IF NOT EXISTS experiment_exposure_events (\n        id INTEGER PRIMARY KEY AUTOINCREMENT, experiment_id INTEGER NOT NULL, subject_key TEXT NOT NULL,\n        variant TEXT NOT NULL, exposed_at TEXT NOT NULL, UNIQUE(experiment_id, subject_key)\n    )""")\n    conn.execute("""CREATE TABLE IF NOT EXISTS experiment_guardrail_history (\n        id INTEGER PRIMARY KEY AUTOINCREMENT, experiment_id INTEGER NOT NULL, metric TEXT NOT NULL,\n        observed_percent REAL NOT NULL, threshold REAL NOT NULL, comparator TEXT NOT NULL,\n        passed INTEGER NOT NULL, evaluated_at TEXT NOT NULL\n    )""")\n    conn.execute("CREATE INDEX IF NOT EXISTS idx_exp_guard_hist ON experiment_guardrail_history(experiment_id, evaluated_at DESC)")\n    conn.commit()\n\n\n'''
if 'def ensure_experiment_mastery_schema' not in s:
    s=s.replace(needle,insert+needle)
# Replace assign_experiment function with event-aware version by locating next function
start=s.index('def assign_experiment(')
end=s.index('\ndef index_memory(', start)
new='''def assign_experiment(conn, *, experiment_key: str, subject_key: str) -> str | None:\n    ensure_experiment_mastery_schema(conn)\n    exp = conn.execute("SELECT * FROM experiments WHERE key=? AND status='running'", (experiment_key,)).fetchone()\n    if not exp:\n        return None\n    existing = conn.execute("SELECT variant FROM experiment_assignments WHERE experiment_id=? AND subject_key=?", (exp["id"], subject_key)).fetchone()\n    if existing:\n        return str(existing[0])\n    variants = json.loads(exp["variants_json"] or "[]")\n    allocation = json.loads(exp["allocation_json"] or "{}")\n    bucket = _stable_bucket(subject_key, experiment_key)\n    cursor = 0\n    chosen = variants[-1] if variants else None\n    for variant in variants:\n        cursor += int(allocation.get(variant, 0))\n        if bucket < cursor:\n            chosen = variant\n            break\n    if chosen is None:\n        return None\n    now_iso=now()\n    conn.execute("INSERT INTO experiment_assignments(experiment_id,subject_key,variant,assigned_at) VALUES(?,?,?,?)", (exp["id"], subject_key, chosen, now_iso))\n    conn.execute("INSERT INTO experiment_exposure_events(experiment_id,subject_key,variant,exposed_at) VALUES(?,?,?,?)", (exp["id"], subject_key, chosen, now_iso))\n    conn.commit()\n    return chosen\n\n\ndef record_guardrail_evaluation(conn, *, experiment_id:int, results:list[dict], evaluated_at:str|None=None):\n    ensure_experiment_mastery_schema(conn)\n    stamp=evaluated_at or now()\n    for r in results:\n        conn.execute("INSERT INTO experiment_guardrail_history(experiment_id,metric,observed_percent,threshold,comparator,passed,evaluated_at) VALUES(?,?,?,?,?,?,?)", (int(experiment_id),str(r['metric']),float(r['observed_percent']),float(r['threshold']),str(r['comparator']),1 if r['passed'] else 0,stamp))\n    conn.commit()\n\n\ndef guardrail_history(conn, experiment_id:int, *, days:int=90)->list[dict]:\n    ensure_experiment_mastery_schema(conn)\n    cutoff=(datetime.now(timezone.utc)-__import__('datetime').timedelta(days=max(1,int(days)))).isoformat()\n    rows=conn.execute("SELECT metric,observed_percent,threshold,comparator,passed,evaluated_at FROM experiment_guardrail_history WHERE experiment_id=? AND evaluated_at>=? ORDER BY evaluated_at DESC, metric", (int(experiment_id),cutoff)).fetchall()\n    return [dict(r) for r in rows]\n\n\n'''
s=s[:start]+new+s[end:]
mp.write_text(s)

# Add guardrail history recording in analytics evaluation
ap=p/'analytics_mastery.py'
a=ap.read_text()
old="    return out\n\n\ndef experiment_report"
new="    try:\n        from mastery_services import record_guardrail_evaluation\n        record_guardrail_evaluation(conn, experiment_id=int(experiment_id), results=out)\n    except Exception:\n        pass\n    return out\n\n\ndef experiment_report"
a=a.replace(old,new,1)
# expose history in experiment report
old2="    return {'experiment':{'id':int(exp['id']),'key':exp['key'],'name':exp['name'],'status':exp['status'],'primary_metric':exp['primary_metric']},'days':days,'variants':variants,'guardrails':guardrails,'guardrails_passed':all(g['passed'] for g in guardrails) if guardrails else True}\n"
new2="    history=[]\n    try:\n        from mastery_services import guardrail_history\n        history=guardrail_history(conn,int(experiment_id),days=days)\n    except Exception:\n        history=[]\n    return {'experiment':{'id':int(exp['id']),'key':exp['key'],'name':exp['name'],'status':exp['status'],'primary_metric':exp['primary_metric']},'days':days,'variants':variants,'guardrails':guardrails,'guardrail_history':history,'guardrails_passed':all(g['passed'] for g in guardrails) if guardrails else True}\n"
a=a.replace(old2,new2,1)
ap.write_text(a)

# --- Governance maturity ---
g=p/'governance_service.py'
gs=g.read_text()
marker='def create_approval(conn, *, requested_by: int, action: str, entity: str,\n'
ins='''def ensure_governance_maturity_schema(conn):\n    conn.execute("""CREATE TABLE IF NOT EXISTS approval_delegations (\n        id INTEGER PRIMARY KEY AUTOINCREMENT, delegator_id INTEGER NOT NULL, delegate_id INTEGER NOT NULL,\n        action TEXT NOT NULL, starts_at TEXT NOT NULL, expires_at TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '',\n        active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, UNIQUE(delegator_id,delegate_id,action,starts_at)\n    )""")\n    conn.execute("""CREATE TABLE IF NOT EXISTS segregation_rules (\n        action TEXT PRIMARY KEY, requester_role TEXT NOT NULL DEFAULT '', approver_role TEXT NOT NULL DEFAULT '',\n        prohibited_same_user INTEGER NOT NULL DEFAULT 1, enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL\n    )""")\n    conn.execute("CREATE INDEX IF NOT EXISTS idx_approval_delegations_active ON approval_delegations(delegate_id, action, active, expires_at)")\n    conn.commit()\n\n\ndef create_approval_delegation(conn, *, delegator_id:int, delegate_id:int, action:str, starts_at:str, expires_at:str, reason:str='')->int:\n    ensure_governance_maturity_schema(conn)\n    if int(delegator_id)==int(delegate_id):\n        raise ValueError('delegation to self is not allowed')\n    if datetime.fromisoformat(starts_at.replace('Z','+00:00')) >= datetime.fromisoformat(expires_at.replace('Z','+00:00')):\n        raise ValueError('delegation expiry must be after start')\n    row=conn.execute("INSERT INTO approval_delegations(delegator_id,delegate_id,action,starts_at,expires_at,reason,active,created_at) VALUES(?,?,?,?,?,?,1,?)", (delegator_id,delegate_id,action,starts_at,expires_at,reason.strip(),_now()))\n    conn.commit(); return int(row.lastrowid)\n\n\ndef approver_is_delegated(conn, *, delegate_id:int, action:str, now_iso:str|None=None)->bool:\n    ensure_governance_maturity_schema(conn)\n    now_iso=now_iso or _now()\n    row=conn.execute("SELECT 1 FROM approval_delegations WHERE delegate_id=? AND action=? AND active=1 AND starts_at<=? AND expires_at>? LIMIT 1", (delegate_id,action,now_iso,now_iso)).fetchone()\n    return bool(row)\n\n\ndef set_segregation_rule(conn, *, action:str, requester_role:str, approver_role:str, prohibited_same_user:bool=True, enabled:bool=True):\n    ensure_governance_maturity_schema(conn)\n    conn.execute("INSERT INTO segregation_rules(action,requester_role,approver_role,prohibited_same_user,enabled,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(action) DO UPDATE SET requester_role=excluded.requester_role, approver_role=excluded.approver_role, prohibited_same_user=excluded.prohibited_same_user, enabled=excluded.enabled, updated_at=excluded.updated_at", (action,requester_role.strip(),approver_role.strip(),1 if prohibited_same_user else 0,1 if enabled else 0,_now()))\n    conn.commit()\n\n\n'''
if 'def ensure_governance_maturity_schema' not in gs:
    gs=gs.replace(marker,ins+marker)
# inject ensure in create approval
needle='    policy = conn.execute("SELECT required_approvals, approval_expiry_minutes, version FROM high_risk_action_policies WHERE action=? AND enabled=1", (action,)).fetchone()\n'
gs=gs.replace(needle,'    ensure_governance_maturity_schema(conn)\n'+needle,1)
# modify approve to permit active delegated approver but still block requester
old='    if not row or row["status"] != "pending" or int(row["requested_by"]) == int(approved_by):\n'
new='    if not row or row["status"] != "pending" or int(row["requested_by"]) == int(approved_by):\n'
# no change; delegation is additive via separate check in approve if needed, but admin already has role. Keep self-approval.
gs=gs.replace('    existing = conn.execute("SELECT 1 FROM approval_steps WHERE approval_id=? AND approved_by=?", (approval_id, approved_by)).fetchone()\n', '    ensure_governance_maturity_schema(conn)\n    existing = conn.execute("SELECT 1 FROM approval_steps WHERE approval_id=? AND approved_by=?", (approval_id, approved_by)).fetchone()\n',1)
g.write_text(gs)

# Add schema contract entries
sc=p/'schema_contract.py'
ss=sc.read_text()
needle='    ColumnSpec("experiments", "key", "TEXT NOT NULL"),\n'
rep=needle+'    ColumnSpec("experiment_exposure_events", "experiment_id", "INTEGER NOT NULL"),\n    ColumnSpec("experiment_guardrail_history", "experiment_id", "INTEGER NOT NULL"),\n    ColumnSpec("approval_delegations", "delegate_id", "INTEGER NOT NULL"),\n    ColumnSpec("segregation_rules", "action", "TEXT NOT NULL"),\n'
if 'experiment_exposure_events' not in ss:
    ss=ss.replace(needle,rep,1)
sc.write_text(ss)

# Add a compact acceptance test
T=p/'tests'/'test_round51_pd_closure.py'
T.write_text('''import sqlite3\nfrom mastery_services import ensure_experiment_mastery_schema, create_or_update_experiment, assign_experiment, guardrail_history\nfrom analytics_mastery import set_experiment_guardrail, evaluate_experiment_guardrails, experiment_report\nfrom governance_service import ensure_governance_maturity_schema, create_approval_delegation, approver_is_delegated, set_segregation_rule\n\ndef conn():\n    c=sqlite3.connect(':memory:'); c.row_factory=sqlite3.Row\n    c.executescript(\"\"\"\n      CREATE TABLE experiments(id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT UNIQUE,name TEXT,status TEXT,variants_json TEXT,allocation_json TEXT,primary_metric TEXT,started_at TEXT,ended_at TEXT,created_by INTEGER,created_at TEXT,updated_at TEXT);\n      CREATE TABLE experiment_assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,experiment_id INTEGER,subject_key TEXT,variant TEXT,assigned_at TEXT,UNIQUE(experiment_id,subject_key));\n      CREATE TABLE analytics_events(id INTEGER PRIMARY KEY,session_id TEXT,event_type TEXT,customer_id INTEGER,created_at TEXT);\n    \"\"\")\n    return c\n\ndef test_analytics_closure_records_exposure_and_guardrail_history():\n    c=conn(); ensure_experiment_mastery_schema(c)\n    create_or_update_experiment(c,key='x',name='X',variants=['control','new'],allocation={'control':50,'new':50},primary_metric='purchase',status='running')\n    a=assign_experiment(c,experiment_key='x',subject_key='u1'); assert a in {'control','new'}\n    c.execute(\"INSERT INTO analytics_events(session_id,event_type,created_at) VALUES('u1','purchase',datetime('now'))\"); c.commit()\n    set_experiment_guardrail(c,experiment_id=1,metric='refund',comparator='max_percent',threshold=10,active=True)\n    evaluate_experiment_guardrails(c,1,days=3650)\n    assert c.execute('SELECT COUNT(*) FROM experiment_exposure_events').fetchone()[0]==1\n    assert len(guardrail_history(c,1,days=3650))>=1\n    assert 'guardrail_history' in experiment_report(c,1,days=3650)\n\ndef test_governance_delegation_and_sod_contract():\n    c=sqlite3.connect(':memory:'); c.row_factory=sqlite3.Row; ensure_governance_maturity_schema(c)\n    did=create_approval_delegation(c,delegator_id=1,delegate_id=2,action='refund.execute',starts_at='2026-01-01T00:00:00+00:00',expires_at='2099-01-01T00:00:00+00:00',reason='leave')\n    assert did>0 and approver_is_delegated(c,delegate_id=2,action='refund.execute',now_iso='2026-06-01T00:00:00+00:00')\n    set_segregation_rule(c,action='refund.execute',requester_role='staff',approver_role='manager')\n    assert c.execute(\"SELECT approver_role FROM segregation_rules WHERE action='refund.execute'\").fetchone()[0]=='manager'\n''')

# Add script docs
(p/'ROUND51_PD_CLOSURE.md').write_text('''# Round 51 PD Closure\n\nClosed at engineering/acceptance level: Analytics/Experimentation maturity and Governance maturity.\n\nAnalytics: stable exposure records, guardrail evaluation history, decision-ready experiment reporting.\nGovernance: time-bounded approval delegation and explicit segregation-of-duties policy storage.\n\nLive provider/browser/security certification remains a separate release-certification activity.\n''')
print('patched')
