from pathlib import Path
root=Path('/mnt/data/round36_work')

# 1) Add financial ledger tables/schema.
db=root/'database.py'; s=db.read_text()
needle='CREATE TABLE IF NOT EXISTS financial_reconciliation ('
insert='''CREATE TABLE IF NOT EXISTS financial_ledger (\n      id INTEGER PRIMARY KEY AUTOINCREMENT,\n      entry_key TEXT NOT NULL UNIQUE,\n      entry_type TEXT NOT NULL,\n      order_id INTEGER REFERENCES orders(id),\n      refund_id INTEGER REFERENCES order_refunds(id),\n      provider TEXT NOT NULL DEFAULT 'razorpay',\n      provider_reference TEXT NOT NULL DEFAULT '',\n      amount INTEGER NOT NULL,\n      currency TEXT NOT NULL DEFAULT 'INR',\n      occurred_at TEXT NOT NULL,\n      created_at TEXT NOT NULL,\n      metadata_json TEXT NOT NULL DEFAULT '{}'\n  );\n  CREATE INDEX IF NOT EXISTS idx_financial_ledger_order ON financial_ledger(order_id, occurred_at);\n  CREATE INDEX IF NOT EXISTS idx_financial_ledger_type ON financial_ledger(entry_type, occurred_at);\n\n  CREATE TABLE IF NOT EXISTS financial_ledger_snapshots (\n      id INTEGER PRIMARY KEY AUTOINCREMENT,\n      period_start TEXT NOT NULL,\n      period_end TEXT NOT NULL,\n      gross_sales INTEGER NOT NULL DEFAULT 0,\n      refunds INTEGER NOT NULL DEFAULT 0,\n      net_sales INTEGER NOT NULL DEFAULT 0,\n      ledger_entries INTEGER NOT NULL DEFAULT 0,\n      created_at TEXT NOT NULL,\n      UNIQUE(period_start, period_end)\n  );\n  CREATE INDEX IF NOT EXISTS idx_ledger_snapshots_period ON financial_ledger_snapshots(period_start, period_end);\n\n  '''
if 'CREATE TABLE IF NOT EXISTS financial_ledger (' not in s:
    s=s.replace(needle, insert+needle, 1)
db.write_text(s)

# 2) Add schema contract entries.
sc=root/'schema_contract.py'; s=sc.read_text()
marker='ColumnSpec("financial_reconciliation", "id", "INTEGER"),'
addition='''ColumnSpec("financial_ledger", "id", "INTEGER"),\n    ColumnSpec("financial_ledger", "entry_key", "TEXT NOT NULL"),\n    ColumnSpec("financial_ledger", "entry_type", "TEXT NOT NULL"),\n    ColumnSpec("financial_ledger", "order_id", "INTEGER"),\n    ColumnSpec("financial_ledger", "refund_id", "INTEGER"),\n    ColumnSpec("financial_ledger", "amount", "INTEGER NOT NULL"),\n    ColumnSpec("financial_ledger", "currency", "TEXT NOT NULL DEFAULT 'INR'"),\n    ColumnSpec("financial_ledger", "occurred_at", "TEXT NOT NULL"),\n    ColumnSpec("financial_ledger_snapshots", "id", "INTEGER"),\n    ColumnSpec("financial_ledger_snapshots", "period_start", "TEXT NOT NULL"),\n    ColumnSpec("financial_ledger_snapshots", "period_end", "TEXT NOT NULL"),\n    ColumnSpec("financial_ledger_snapshots", "gross_sales", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("financial_ledger_snapshots", "refunds", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("financial_ledger_snapshots", "net_sales", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("financial_ledger_snapshots", "ledger_entries", "INTEGER NOT NULL DEFAULT 0"),\n'''
if 'ColumnSpec("financial_ledger"' not in s:
    s=s.replace(marker, addition+marker,1)
sc.write_text(s)

# 3) Add ledger helpers to reconciliation module and snapshot each run.
rr=root/'reconcile_razorpay.py'; s=rr.read_text()
helper='''\n\ndef _ledger_entry(conn, *, entry_key, entry_type, order_id=None, refund_id=None, provider_reference="", amount=0, occurred_at=None, metadata=None):\n    conn.execute(\n        """INSERT OR IGNORE INTO financial_ledger\n           (entry_key,entry_type,order_id,refund_id,provider,provider_reference,amount,currency,occurred_at,created_at,metadata_json)\n           VALUES(?,?,?,?,?,?,?,?,?,?,?)""",\n        (str(entry_key), str(entry_type), order_id, refund_id, "razorpay", str(provider_reference or ""), int(amount or 0), "INR", occurred_at or _now(), _now(), json.dumps(metadata or {}, sort_keys=True, default=str)),\n    )\n\n\ndef refresh_ledger_snapshot(conn, *, period_start, period_end):\n    sales = int(conn.execute("SELECT COALESCE(SUM(amount),0) AS v FROM financial_ledger WHERE entry_type='sale' AND occurred_at>=? AND occurred_at<?", (period_start, period_end)).fetchone()["v"] or 0)\n    refunds = int(conn.execute("SELECT COALESCE(SUM(amount),0) AS v FROM financial_ledger WHERE entry_type='refund' AND occurred_at>=? AND occurred_at<?", (period_start, period_end)).fetchone()["v"] or 0)\n    entries = int(conn.execute("SELECT COUNT(*) AS v FROM financial_ledger WHERE occurred_at>=? AND occurred_at<?", (period_start, period_end)).fetchone()["v"] or 0)\n    conn.execute("INSERT INTO financial_ledger_snapshots(period_start,period_end,gross_sales,refunds,net_sales,ledger_entries,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(period_start,period_end) DO UPDATE SET gross_sales=excluded.gross_sales,refunds=excluded.refunds,net_sales=excluded.net_sales,ledger_entries=excluded.ledger_entries,created_at=excluded.created_at", (period_start,period_end,sales,refunds,sales-refunds,entries,_now()))\n    return {"gross_sales": sales, "refunds": refunds, "net_sales": sales-refunds, "ledger_entries": entries}\n\n\ndef ledger_snapshot(period_start: str, period_end: str):\n    conn=db.get_db(); row=conn.execute("SELECT * FROM financial_ledger_snapshots WHERE period_start=? AND period_end=?", (period_start,period_end)).fetchone(); conn.close()\n    return dict(row) if row else None\n'''
if 'def _ledger_entry' not in s:
    s += helper
# Inject ledger sale entry after successful capture-state discovery/recovery before refund logic.
needle='            payment_id=order["razorpay_payment_id"] or (captured[0].get("id") if captured else None)\n'
repl='''            payment_id=order["razorpay_payment_id"] or (captured[0].get("id") if captured else None)\n            if captured and payment_id:\n                capture_ref = payment_id\n                _ledger_entry(conn, entry_key=f"sale:{oid}:{capture_ref}", entry_type="sale", order_id=oid, provider_reference=capture_ref, amount=int(order["amount"] or 0), occurred_at=order["paid_at"] or order["created_at"], metadata={"source":"razorpay_reconciliation"})\n'''
s=s.replace(needle,repl,1)
# Add refund ledger inside refund fetch loop after provider_ids
needle='                    provider_ids={r.get("id") for r in provider_refunds if r.get("id")}\n'
repl='''                    provider_ids={r.get("id") for r in provider_refunds if r.get("id")}\n                    for provider_ref in provider_refunds:\n                        pref = provider_ref.get("id")\n                        if pref and str(provider_ref.get("status") or "").lower() in {"processed","refunded"}:\n                            _ledger_entry(conn, entry_key=f"refund:{oid}:{pref}", entry_type="refund", order_id=oid, provider_reference=pref, amount=int(provider_ref.get("amount") or 0)//100, occurred_at=provider_ref.get("created_at") and datetime.fromtimestamp(int(provider_ref.get("created_at")), tz=timezone.utc).isoformat() or _now(), metadata={"source":"razorpay_reconciliation"})\n'''
s=s.replace(needle,repl,1)
# snapshot for run after inventory consistency.
needle='        mismatches += reconcile_inventory_consistency(conn, run_id=int(run_id))\n        result='
repl='''        mismatches += reconcile_inventory_consistency(conn, run_id=int(run_id))\n        snapshot = refresh_ledger_snapshot(conn, period_start="0000-01-01T00:00:00+00:00", period_end="9999-12-31T23:59:59+00:00")\n        result='''
s=s.replace(needle,repl,1)
s=s.replace('result = {"status":"completed","run_id":int(run_id),"repaired":repaired,"mismatches":mismatches,"scanned":scanned}', 'result = {"status":"completed","run_id":int(run_id),"repaired":repaired,"mismatches":mismatches,"scanned":scanned,"ledger":snapshot}',1)
rr.write_text(s)

# 4) Add a safe refund workflow wrapper around existing implementation.
rf=root/'payment/refund.py'; s=rf.read_text()
if 'def _process_refund_impl' not in s:
    s=s.replace('def process_refund(conn, refund_id: int, provider_refund_id: Optional[str] = None) -> Dict[str, Any]:', 'def _process_refund_impl(conn, refund_id: int, provider_refund_id: Optional[str] = None) -> Dict[str, Any]:',1)
    insert='''\n\n# Durable workflow wrapper: the existing refund implementation remains the\n# business-state authority; the workflow adds persistence/recovery around it.\ndef process_refund(conn, refund_id: int, provider_refund_id: Optional[str] = None) -> Dict[str, Any]:\n    try:\n        from titan_workflows import DurableWorkflow, WorkflowStep\n        refund = conn.execute("SELECT * FROM order_refunds WHERE id=?", (int(refund_id),)).fetchone()\n        if not refund:\n            return {"success": False, "error": "Refund not found"}\n        flow = DurableWorkflow(conn, workflow_type="order.refund", aggregate_type="refund", aggregate_id=str(refund_id))\n        def execute(_conn, ctx):\n            return _process_refund_impl(_conn, refund_id, provider_refund_id)\n        result = flow.run([WorkflowStep("process_refund", execute)])\n        if result.get("status") == "completed":\n            return dict(result.get("context") or {}).get("result") or _process_refund_impl(conn, refund_id, provider_refund_id)\n        if result.get("status") == "waiting":\n            return {"success": True, "refund_id": refund_id, "status": "pending", "workflow_id": result.get("workflow_id")}\n        return result\n    except Exception as exc:\n        logger.exception("Durable refund workflow failed")\n        # Preserve the historical API surface while the durable workflow state\n        # records the failure. Do not retry the provider call implicitly here.\n        return {"success": False, "refund_id": refund_id, "status": "failed", "error": str(exc)[:500]}\n'''
    s=s.replace('\ndef get_refund_status', insert+'\n\ndef get_refund_status',1)
    # Make workflow step retain actual result in context: alter execute return wrapper.
    s=s.replace('            return _process_refund_impl(_conn, refund_id, provider_refund_id)', '            result = _process_refund_impl(_conn, refund_id, provider_refund_id)\n            return {"result": result}',1)
rf.write_text(s)

# 5) Add admin finance ledger endpoint.
api=root/'admin_api.py'; s=api.read_text()
if '/governance/ledger' not in s:
    block='''\n\n@admin_api.route("/governance/ledger", methods=["GET"])\n@api_requires_permission("audit.view")\ndef governance_ledger():\n    conn = db.get_db()\n    limit = max(1, min(int(request.args.get("limit", 200)), 1000))\n    rows = conn.execute("SELECT entry_type, order_id, refund_id, provider_reference, amount, currency, occurred_at FROM financial_ledger ORDER BY occurred_at DESC, id DESC LIMIT ?", (limit,)).fetchall()\n    totals = conn.execute("SELECT COALESCE(SUM(CASE WHEN entry_type='sale' THEN amount ELSE 0 END),0) AS gross, COALESCE(SUM(CASE WHEN entry_type='refund' THEN amount ELSE 0 END),0) AS refunds FROM financial_ledger").fetchone()\n    conn.close()\n    return ok({"entries":[dict(r) for r in rows], "gross_sales": int(totals["gross"] or 0), "refunds": int(totals["refunds"] or 0), "net_sales": int(totals["gross"] or 0)-int(totals["refunds"] or 0)})\n'''
    s += block
api.write_text(s)

# 6) Add tests for round37.
t=root/'tests/test_round37_pd.py'; t.write_text('''import sqlite3\nfrom pathlib import Path\n\nroot=Path(__file__).resolve().parents[1]\nc=sqlite3.connect(":memory:")\nc.executescript("""\nCREATE TABLE orders(id INTEGER PRIMARY KEY, order_ref TEXT, amount INTEGER, paid_at TEXT, created_at TEXT, razorpay_order_id TEXT, razorpay_payment_id TEXT, status TEXT);\nCREATE TABLE order_refunds(id INTEGER PRIMARY KEY, order_id INTEGER, amount INTEGER, provider_refund_id TEXT, status TEXT);\nCREATE TABLE admin_users(id INTEGER PRIMARY KEY);\n""")\nledger_sql=(root/'database.py').read_text()\nassert 'CREATE TABLE IF NOT EXISTS financial_ledger' in ledger_sql\nfrom reconcile_razorpay import _ledger_entry, refresh_ledger_snapshot\n_ledger_entry(c, entry_key='sale:1:p1', entry_type='sale', order_id=1, provider_reference='p1', amount=500, occurred_at='2026-01-01T00:00:00+00:00')\n_ledger_entry(c, entry_key='refund:1:r1', entry_type='refund', order_id=1, provider_reference='r1', amount=100, occurred_at='2026-01-02T00:00:00+00:00')\nrow=refresh_ledger_snapshot(c, period_start='0000', period_end='9999')\nassert row['gross_sales']==500 and row['refunds']==100 and row['net_sales']==400\nfrom titan_workflows import DurableWorkflow, WorkflowStep\nflow=DurableWorkflow(c, workflow_type='order.refund', aggregate_type='refund', aggregate_id='9')\nres=flow.run([WorkflowStep('process_refund', lambda conn,ctx: {'result': {'success': True}})])\nassert res['status']=='completed'\nprint('Round37 PD checks: PASS')\n''')

print('patched')
