from pathlib import Path
root=Path('/mnt/data/round24_work/round23_work')

# 1) Extend schema contract and database schema for reconciliation resolution + workflow adoption metadata.
p=root/'schema_contract.py'
s=p.read_text()
s=s.replace('ColumnSpec("workflow_runs", "current_step", "INTEGER NOT NULL DEFAULT 0"),', 'ColumnSpec("workflow_runs", "current_step", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("workflow_runs", "attempt_count", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("workflow_runs", "compensation_status", "TEXT NOT NULL DEFAULT \'not_needed\'"),')
s=s.replace('ColumnSpec("reconciliation_items", "code", "TEXT NOT NULL"),', 'ColumnSpec("reconciliation_items", "code", "TEXT NOT NULL"),\n    ColumnSpec("reconciliation_items", "resolved", "INTEGER NOT NULL DEFAULT 0"),\n    ColumnSpec("reconciliation_items", "resolution", "TEXT NOT NULL DEFAULT \'\'"),\n    ColumnSpec("reconciliation_items", "resolved_by", "INTEGER"),\n    ColumnSpec("reconciliation_items", "resolved_at", "TEXT"),')
p.write_text(s)

p=root/'database.py'; s=p.read_text()
# add migration statements before closing list marker near workflow additions
needle='    "ALTER TABLE business_exceptions ADD COLUMN escalation_reason TEXT NOT NULL DEFAULT \'\'",\n'
insert=needle+'    "ALTER TABLE reconciliation_items ADD COLUMN resolution TEXT NOT NULL DEFAULT \'\'",\n    "ALTER TABLE reconciliation_items ADD COLUMN resolved_by INTEGER REFERENCES admin_users(id)",\n    "ALTER TABLE reconciliation_items ADD COLUMN resolved_at TEXT",\n'
s=s.replace(needle, insert, 1)
# Add indexes and ensure helper after ensure_round22_schema region by locating ensure_round19? We'll add a round24 schema helper after ensure_round18_schema.
marker='def ensure_round22_schema(conn):\n'
helper='''SCHEMA_EXTRA_ROUND24 = """\n  ALTER TABLE reconciliation_items ADD COLUMN resolution TEXT NOT NULL DEFAULT '';\n  ALTER TABLE reconciliation_items ADD COLUMN resolved_by INTEGER;\n  ALTER TABLE reconciliation_items ADD COLUMN resolved_at TEXT;\n  CREATE INDEX IF NOT EXISTS idx_reconciliation_items_status ON reconciliation_items(run_id, resolved, id);\n"""\n\ndef ensure_round24_schema(conn):\n    for stmt in SCHEMA_EXTRA_ROUND24.split(';'):\n        stmt = stmt.strip()\n        if not stmt:\n            continue\n        try:\n            conn.execute(stmt)\n        except Exception as exc:\n            msg = str(exc).lower()\n            if 'duplicate column' not in msg and 'already exists' not in msg:\n                raise\n    conn.commit()\n\n\n'''
s=s.replace(marker, helper+marker, 1)
# ensure schema in database get_db initialization where round schemas are called
# inject call after ensure_round22_schema(conn) if present
s=s.replace('    ensure_round22_schema(conn)\n', '    ensure_round22_schema(conn)\n    ensure_round24_schema(conn)\n', 1)
p.write_text(s)

# 2) Durable workflow: add canonical waiting state + status helper + resume-safe run semantics.
p=root/'titan_workflows.py'; s=p.read_text()
# Add WAIT sentinel
s=s.replace('class WorkflowError(RuntimeError):\n    pass\n', '''class WorkflowError(RuntimeError):\n    pass\n\n\nclass WorkflowWaiting:\n    """Signal that a workflow has reached an external wait state."""\n    def __init__(self, reason: str = "waiting for external event"):\n        self.reason = reason\n\n\nWAIT = object()\n''')
# add status method before run
s=s.replace('    def run(self, steps: Iterable[WorkflowStep], *, context: dict | None = None) -> dict:\n', '''    def status(self) -> dict:\n        row = self._load()\n        if not row:\n            return {"workflow_id": self.workflow_id, "status": "pending", "current_step": 0, "context": {}}\n        return {"workflow_id": self.workflow_id, "status": row["status"], "current_step": int(row["current_step"] or 0), "context": json.loads(row["context_json"] or "{}"), "error": row["error"] or "", "compensation_status": row["compensation_status"] or "not_needed"}\n\n    def run(self, steps: Iterable[WorkflowStep], *, context: dict | None = None) -> dict:\n''')
# waiting behavior after result=step.run
old='''                result = step.run(self.conn, ctx)\n                if isinstance(result, dict):\n                    ctx.update(result)\n'''
new='''                result = step.run(self.conn, ctx)\n                if isinstance(result, WorkflowWaiting):\n                    self.conn.execute(\n                        "UPDATE workflow_steps SET status='waiting',result_json=?,completed_at=NULL WHERE workflow_id=? AND step_index=?",\n                        (json.dumps({"reason": result.reason}, sort_keys=True), self.workflow_id, index),\n                    )\n                    self.conn.execute(\n                        "UPDATE workflow_runs SET status='waiting',current_step=?,context_json=?,updated_at=?,error='' WHERE workflow_id=?",\n                        (index, json.dumps(ctx, sort_keys=True, default=str), _now(), self.workflow_id),\n                    )\n                    self.conn.commit()\n                    return {"workflow_id": self.workflow_id, "status": "waiting", "context": ctx, "reason": result.reason}\n                if isinstance(result, dict):\n                    ctx.update(result)\n'''
s=s.replace(old,new)
s=s.replace('__all__ = ["DurableWorkflow", "WorkflowStep", "WorkflowError"]', '__all__ = ["DurableWorkflow", "WorkflowStep", "WorkflowError", "WorkflowWaiting", "WAIT"]')
p.write_text(s)

# 3) Add a commerce workflow adapter and use it in payment confirmation paths.
newfile=root/'commerce_workflows.py'
newfile.write_text('''"""Canonical durable workflows for critical commerce transitions."""\nfrom __future__ import annotations\n\nfrom titan_workflows import DurableWorkflow, WorkflowStep, WorkflowError\n\n\ndef confirm_order_payment_durable(conn, *, order, order_items, payment_mode="gateway", razorpay_payment_id=None, razorpay_signature=None, confirm_callable):\n    """Run the existing idempotent payment finalizer under durable workflow control.\n\n    The legacy finalizer remains authoritative for business-state mutations; the\n    workflow adds resumability, auditability and step state without duplicating\n    financial logic.\n    """\n    flow = DurableWorkflow(conn, workflow_type="order.payment_confirmation", aggregate_type="order", aggregate_id=order["order_ref"])\n\n    def finalize(_conn, ctx):\n        msg = confirm_callable(_conn, order, order_items, payment_mode=payment_mode,\n                               razorpay_payment_id=razorpay_payment_id, razorpay_signature=razorpay_signature)\n        return {"order_id": int(order["id"]), "order_ref": order["order_ref"], "payment_mode": payment_mode, "delivery_message": msg or ""}\n\n    try:\n        return flow.run([WorkflowStep("finalize_payment_and_fulfillment", finalize)])\n    except WorkflowError:\n        raise\n\n\ndef workflow_status(conn, order_ref: str) -> dict:\n    flow = DurableWorkflow(conn, workflow_type="order.payment_confirmation", aggregate_type="order", aggregate_id=order_ref, workflow_id=next((r["workflow_id"] for r in conn.execute("SELECT workflow_id FROM workflow_runs WHERE workflow_type='order.payment_confirmation' AND aggregate_type='order' AND aggregate_id=? ORDER BY updated_at DESC LIMIT 1", (str(order_ref),)).fetchall()), None)) if conn.execute("SELECT 1 FROM workflow_runs WHERE workflow_type='order.payment_confirmation' AND aggregate_type='order' AND aggregate_id=? LIMIT 1", (str(order_ref),)).fetchone() else None\n    return flow.status() if flow else {"workflow_id": None, "status": "not_started", "context": {}}\n''')
# The above uses a slightly awkward constructor expression; simplify after write.
s=newfile.read_text()
s=s.replace('''def workflow_status(conn, order_ref: str) -> dict:\n    flow = DurableWorkflow(conn, workflow_type="order.payment_confirmation", aggregate_type="order", aggregate_id=order_ref, workflow_id=next((r["workflow_id"] for r in conn.execute("SELECT workflow_id FROM workflow_runs WHERE workflow_type=\'order.payment_confirmation\' AND aggregate_type=\'order\' AND aggregate_id=? ORDER BY updated_at DESC LIMIT 1", (str(order_ref),)).fetchall()), None)) if conn.execute("SELECT 1 FROM workflow_runs WHERE workflow_type=\'order.payment_confirmation\' AND aggregate_type=\'order\' AND aggregate_id=? LIMIT 1", (str(order_ref),)).fetchone() else None\n    return flow.status() if flow else {"workflow_id": None, "status": "not_started", "context": {}}\n''','''def workflow_status(conn, order_ref: str) -> dict:\n    row = conn.execute("SELECT workflow_id FROM workflow_runs WHERE workflow_type='order.payment_confirmation' AND aggregate_type='order' AND aggregate_id=? ORDER BY updated_at DESC LIMIT 1", (str(order_ref),)).fetchone()\n    if not row:\n        return {"workflow_id": None, "status": "not_started", "context": {}}\n    return DurableWorkflow(conn, workflow_type="order.payment_confirmation", aggregate_type="order", aggregate_id=order_ref, workflow_id=row["workflow_id"]).status()\n''')
newfile.write_text(s)

# replace payment confirmation calls, preserving wrapper internal definition
p=root/'blueprints/storefront.py'; s=p.read_text()
# add import
anchor='from storefront_service import get_primary_image_map\n'
s=s.replace(anchor, anchor+'from commerce_workflows import confirm_order_payment_durable\n',1)
s=s.replace('        _confirm_order_payment(conn, order, order_items, payment_mode="test")', '        confirm_order_payment_durable(conn, order=order, order_items=order_items, payment_mode="test", confirm_callable=_confirm_order_payment)', 2)
s=s.replace('        _confirm_order_payment(conn, order, order_items, payment_mode="gateway", razorpay_payment_id=razorpay_payment_id, razorpay_signature="")', '        confirm_order_payment_durable(conn, order=order, order_items=order_items, payment_mode="gateway", razorpay_payment_id=razorpay_payment_id, razorpay_signature="", confirm_callable=_confirm_order_payment)', 1)
# Gateway verify has auto_message assignment; replace multiline exact start
s=s.replace('        auto_message = _confirm_order_payment(\n            conn, order, order_items,\n            payment_mode="gateway",\n            razorpay_payment_id=rzp_payment_id,\n            razorpay_signature=rzp_signature,\n        )', '        workflow_result = confirm_order_payment_durable(conn, order=order, order_items=order_items, payment_mode="gateway", razorpay_payment_id=rzp_payment_id, razorpay_signature=rzp_signature, confirm_callable=_confirm_order_payment)\n        auto_message = ((workflow_result.get("context") or {}).get("delivery_message") if isinstance(workflow_result, dict) else None)')
p.write_text(s)

# 4) Reconciliation resolution + scheduled runner.
p=root/'reconcile_razorpay.py'; s=p.read_text()
s=s.replace('    db.ensure_round18_schema(conn)', '    db.ensure_round18_schema(conn)\n    db.ensure_round24_schema(conn)', 1)
# append resolution functions
s += '''\n\ndef get_open_items(*, run_id=None, limit=200):\n    conn = db.get_db(); db.ensure_round24_schema(conn)\n    if run_id is None:\n        rows = conn.execute("SELECT * FROM reconciliation_items WHERE resolved=0 ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, id DESC LIMIT ?", (max(1, min(int(limit), 500)),)).fetchall()\n    else:\n        rows = conn.execute("SELECT * FROM reconciliation_items WHERE run_id=? AND resolved=0 ORDER BY id DESC", (int(run_id),)).fetchall()\n    data=[dict(r) for r in rows]; conn.close(); return data\n\n\ndef resolve_item(item_id: int, *, resolved_by: int, resolution: str) -> bool:\n    conn = db.get_db(); db.ensure_round24_schema(conn)\n    row=conn.execute("SELECT id, resolved FROM reconciliation_items WHERE id=?", (int(item_id),)).fetchone()\n    if not row or int(row["resolved"] or 0):\n        conn.close(); return False\n    conn.execute("UPDATE reconciliation_items SET resolved=1,resolution=?,resolved_by=?,resolved_at=? WHERE id=?", (str(resolution or "Resolved after manual review")[:4000], int(resolved_by), _now(), int(item_id)))\n    conn.commit(); conn.close(); return True\n'''
p.write_text(s)

# 5) Admin reconciliation UI: run, inspect unresolved, resolve.
p=root/'blueprints/admin.py'; s=p.read_text()
old='''    runs = conn.execute("SELECT id, provider, mode, status, started_at, completed_at, scanned_orders, repaired_orders, mismatches, summary_json FROM reconciliation_runs ORDER BY started_at DESC LIMIT 50").fetchall()\n    conn.close()\n    return render_template("admin/reconciliation.html", runs=runs, result=result)\n'''
new='''    from reconcile_razorpay import get_open_items\n    runs = conn.execute("SELECT id, provider, mode, status, started_at, completed_at, scanned_orders, repaired_orders, mismatches, summary_json FROM reconciliation_runs ORDER BY started_at DESC LIMIT 50").fetchall()\n    open_items = get_open_items(limit=100)\n    conn.close()\n    return render_template("admin/reconciliation.html", runs=runs, result=result, open_items=open_items)\n\n\n@admin_bp.route("/reconciliation/items/<int:item_id>/resolve", methods=["POST"])\n@login_required\n@requires_permission("audit.view")\ndef admin_reconciliation_resolve(item_id):\n    check_csrf()\n    from reconcile_razorpay import resolve_item\n    resolution = (request.form.get("resolution") or "Resolved after manual review").strip()\n    if not resolution:\n        flash("Resolution note is required.", "error")\n        return redirect(url_for("admin.admin_reconciliation"))\n    if resolve_item(item_id, resolved_by=int(session["admin_id"]), resolution=resolution):\n        log_admin_action("reconciliation.item.resolve", "reconciliation_item", item_id, {"resolution": resolution[:500]})\n        flash("Reconciliation discrepancy marked resolved.", "success")\n    else:\n        flash("Reconciliation discrepancy was already resolved or no longer exists.", "error")\n    return redirect(url_for("admin.admin_reconciliation"))\n'''
if old not in s: raise SystemExit('admin reconciliation block not found')
s=s.replace(old,new,1)
p.write_text(s)

# 6) Reconciliation template richer + professional HTML.
p=root/'templates/admin/reconciliation.html'; p.write_text('''{% extends "admin/base.html" %}\n{% block title %}Reconciliation{% endblock %}\n{% block content %}\n<div class="admin-topbar">\n  <div><h1>Payment Reconciliation</h1><p class="muted">Compare provider truth with local orders and refunds. TITAN never silently repairs financial mismatches.</p></div>\n  <form method="POST"><input type="hidden" name="csrf_token" value="{{ csrf_token() }}"><button class="admin-btn admin-btn--primary" type="submit">Run reconciliation</button></form>\n</div>\n<section class="card-box"><h3>Open discrepancies</h3>\n{% if open_items %}<div class="table-wrap"><table class="admin-table"><thead><tr><th>Severity</th><th>Issue</th><th>Entity</th><th>Details</th><th>Action</th></tr></thead><tbody>\n{% for i in open_items %}<tr><td>{{ i.severity }}</td><td><strong>{{ i.title }}</strong><div class="muted">{{ i.code }}</div></td><td>{{ i.entity }}{% if i.entity_id %} #{{ i.entity_id }}{% endif %}</td><td>{{ i.details }}</td><td><form method="POST" action="{{ url_for('admin.admin_reconciliation_resolve', item_id=i.id) }}"><input type="hidden" name="csrf_token" value="{{ csrf_token() }}"><input name="resolution" required placeholder="Resolution note"><button class="admin-btn admin-btn--small" type="submit">Resolve</button></form></td></tr>{% endfor %}\n</tbody></table></div>{% else %}<p>No unresolved reconciliation discrepancies.</p>{% endif %}\n</section>\n<section class="card-box"><h3>Recent runs</h3>\n{% if runs %}<div class="table-wrap"><table class="admin-table"><thead><tr><th>Started</th><th>Provider</th><th>Status</th><th>Scanned</th><th>Repaired</th><th>Mismatches</th></tr></thead><tbody>{% for r in runs %}<tr><td>{{ r.started_at }}</td><td>{{ r.provider }}</td><td>{{ r.status }}</td><td>{{ r.scanned_orders }}</td><td>{{ r.repaired_orders }}</td><td>{{ r.mismatches }}</td></tr>{% endfor %}</tbody></table></div>{% else %}<p>No reconciliation runs yet.</p>{% endif %}</section>\n{% endblock %}\n''')

# 7) Scheduled reconciliation script + Render cron blueprint. Render cron schedules use UTC.
(root/'scripts/run_reconciliation.py').write_text('''#!/usr/bin/env python3\n"""Run scheduled provider reconciliation and exit with a meaningful status."""\nfrom __future__ import annotations\nimport json\nfrom reconcile_razorpay import reconcile\n\nresult = reconcile(created_by=0, mode="scheduled", order_limit=5000)\nprint(json.dumps(result, sort_keys=True, default=str))\nif result.get("status") == "failed":\n    raise SystemExit(2)\n# Skipped is valid when payments are intentionally not configured in an environment.\nraise SystemExit(0)\n''')
(root/'render-reconciliation-cron.yaml').write_text('''services:\n  - type: cron\n    name: virtual-store-reconciliation\n    runtime: python\n    schedule: "0 2 * * *"\n    buildCommand: pip install -r requirements.txt\n    startCommand: python scripts/run_reconciliation.py\n    envVars:\n      - key: PYTHON_VERSION\n        value: "3.14.3"\n      - key: SECRET_KEY\n        sync: false\n      - key: RAZORPAY_KEY_ID\n        sync: false\n      - key: RAZORPAY_KEY_SECRET\n        sync: false\n      - key: RAZORPAY_WEBHOOK_SECRET\n        sync: false\n      - key: DATABASE_URL\n        sync: false\n''')

# 8) Round24 mastery gate.
(root/'scripts/check_round24_mastery.py').write_text('''from pathlib import Path\nROOT=Path(__file__).resolve().parents[1]\nchecks={\n"workflow adapter":"commerce_workflows.py",\n"workflow in single order checkout":"confirm_order_payment_durable",\n"workflow in cart checkout":"confirm_order_payment_durable",\n"scheduled reconcile":"scripts/run_reconciliation.py",\n"reconcile cron":"render-reconciliation-cron.yaml",\n"reconciliation resolution":"def resolve_item",\n"reconciliation admin route":"admin_reconciliation_resolve",\n"reconciliation schema extensions":"ALTER TABLE reconciliation_items ADD COLUMN resolution",\n}\ntext="\n".join((ROOT / f).read_text(errors="ignore") if (ROOT/f).exists() else "" for f in checks if (ROOT/f).exists())\nfailed=[(k,v) for k,v in checks.items() if v not in text]\nif failed:\n    raise SystemExit("Round24 gate failed: "+repr(failed))\nprint("Round24 mastery gate: PASS")\n''')
