from pathlib import Path
root=Path('/mnt/data/round32')
# governance additions
p=root/'governance_service.py'; s=p.read_text()
marker='def run_guardian_scan(conn) -> Dict[str, Any]:\n'
insert='''def ensure_guardian_mastery_schema(conn) -> None:\n    conn.execute("""CREATE TABLE IF NOT EXISTS guardian_detectors (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        code TEXT NOT NULL UNIQUE,\n        title TEXT NOT NULL,\n        severity TEXT NOT NULL DEFAULT 'medium',\n        enabled INTEGER NOT NULL DEFAULT 1,\n        description TEXT NOT NULL DEFAULT '',\n        created_at TEXT NOT NULL,\n        updated_at TEXT NOT NULL\n    )""")\n    conn.execute("""CREATE TABLE IF NOT EXISTS exception_events (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        exception_id INTEGER NOT NULL REFERENCES business_exceptions(id) ON DELETE CASCADE,\n        event_type TEXT NOT NULL,\n        actor_id INTEGER,\n        details_json TEXT NOT NULL DEFAULT '{}',\n        created_at TEXT NOT NULL\n    )""")\n    conn.execute("CREATE INDEX IF NOT EXISTS idx_exception_events_exception ON exception_events(exception_id, created_at)")\n    now=_now()\n    builtins=[\n        ('negative_inventory','Negative inventory','critical','Product stock below zero.'),\n        ('payment_without_paid_order','Payment/order mismatch','high','Provider payment indicates success while local order state does not.'),\n        ('stale_processing_refund','Stale refund','high','Refund remains in processing state beyond the SLA window.'),\n    ]\n    for code,title,severity,description in builtins:\n        conn.execute("INSERT OR IGNORE INTO guardian_detectors(code,title,severity,enabled,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?)", (code,title,severity,1,description,now,now))\n    conn.commit()\n\ndef record_exception_event(conn, exception_id: int, event_type: str, *, actor_id: int | None = None, details: dict | None = None) -> None:\n    ensure_guardian_mastery_schema(conn)\n    conn.execute("INSERT INTO exception_events(exception_id,event_type,actor_id,details_json,created_at) VALUES(?,?,?,?,?)", (int(exception_id), str(event_type), int(actor_id) if actor_id else None, _json(details or {}), _now()))\n    conn.commit()\n\ndef exception_timeline(conn, exception_id: int, limit: int = 100):\n    ensure_guardian_mastery_schema(conn)\n    return conn.execute("""SELECT ev.*, a.username AS actor_name FROM exception_events ev LEFT JOIN admin_users a ON a.id=ev.actor_id WHERE ev.exception_id=? ORDER BY ev.created_at DESC LIMIT ?""", (int(exception_id), max(1,min(int(limit),200)))).fetchall()\n\ndef guardian_detectors(conn):\n    ensure_guardian_mastery_schema(conn)\n    return conn.execute("SELECT * FROM guardian_detectors ORDER BY enabled DESC, severity, title").fetchall()\n\n'''
if 'def ensure_guardian_mastery_schema' not in s:
    s=s.replace(marker, insert+marker)
# instrument lifecycle functions
s=s.replace("    conn.commit()\n    return True\n\n\ndef acknowledge_exception", "    conn.commit()\n    try: record_exception_event(conn, exception_id, 'resolved', actor_id=resolved_by, details={'resolution': resolution.strip()[:1000]})\n    except Exception: pass\n    return True\n\n\ndef acknowledge_exception",1)
s=s.replace("    conn.commit()\n    return True\n\n\ndef reopen_exception", "    conn.commit()\n    try: record_exception_event(conn, exception_id, 'acknowledged', actor_id=admin_id)\n    except Exception: pass\n    return True\n\n\ndef reopen_exception",1)
s=s.replace("    conn.commit()\n    return True\n\n\ndef notify_exception_assignee", "    conn.commit()\n    try: record_exception_event(conn, exception_id, 'reopened', actor_id=admin_id, details={'reason': reason.strip()[:1000]})\n    except Exception: pass\n    return True\n\n\ndef notify_exception_assignee",1)
s=s.replace("    conn.commit(); return True\n\ndef escalate_overdue_exceptions", "    conn.commit()\n    try: record_exception_event(conn, exception_id, 'assigned', details={'assigned_to': int(assigned_to) if assigned_to else None, 'due_at': due_at})\n    except Exception: pass\n    return True\n\ndef escalate_overdue_exceptions",1)
s=s.replace("        conn.execute(\n            \"UPDATE business_exceptions SET severity=?, escalated_at=?, escalation_reason='SLA deadline exceeded', updated_at=? WHERE id=?\",", "        conn.execute(\n            \"UPDATE business_exceptions SET severity=?, escalated_at=?, escalation_reason='SLA deadline exceeded', updated_at=? WHERE id=?\",")
# add event after escalation update block by exact snippet
needle="            (new_severity, now_iso, now_iso, int(row['id'])),\n        )\n        if row['assigned_to']:"
repl="            (new_severity, now_iso, now_iso, int(row['id'])),\n        )\n        try: record_exception_event(conn, int(row['id']), 'escalated', details={'new_severity': new_severity, 'reason': 'SLA deadline exceeded'})\n        except Exception: pass\n        if row['assigned_to']:"
s=s.replace(needle,repl)
# ensure scan schema
s=s.replace('def scan_exceptions(conn) -> int:\n    """Create deduplicated operational exceptions from obvious internal inconsistencies."""\n', 'def scan_exceptions(conn) -> int:\n    """Create deduplicated operational exceptions from obvious internal inconsistencies."""\n    ensure_guardian_mastery_schema(conn)\n')
p.write_text(s)

# observability alert policies
p=root/'observability_service.py'; s=p.read_text()
needle='def start_span(conn, *, trace_id: str, kind: str, name: str, parent_span_id: str | None = None,\n'
insert='''def ensure_alert_policy_schema(conn) -> None:\n    ensure_schema(conn)\n    conn.execute("""CREATE TABLE IF NOT EXISTS observability_alert_policies (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        alert_type TEXT NOT NULL UNIQUE,\n        enabled INTEGER NOT NULL DEFAULT 1,\n        severity TEXT NOT NULL DEFAULT 'medium',\n        threshold_ms INTEGER,\n        cooldown_minutes INTEGER NOT NULL DEFAULT 10,\n        notify_admins INTEGER NOT NULL DEFAULT 1,\n        updated_at TEXT NOT NULL\n    )""")\n    conn.commit()\n\ndef alert_policies(conn):\n    ensure_alert_policy_schema(conn)\n    return conn.execute("SELECT * FROM observability_alert_policies ORDER BY alert_type").fetchall()\n\ndef set_alert_policy(conn, *, alert_type: str, enabled: bool, severity: str, threshold_ms: int | None = None, cooldown_minutes: int = 10, notify_admins: bool = True):\n    ensure_alert_policy_schema(conn)\n    now=now_iso()\n    conn.execute("""INSERT INTO observability_alert_policies(alert_type,enabled,severity,threshold_ms,cooldown_minutes,notify_admins,updated_at) VALUES(?,?,?,?,?,?,?)\n        ON CONFLICT(alert_type) DO UPDATE SET enabled=excluded.enabled,severity=excluded.severity,threshold_ms=excluded.threshold_ms,cooldown_minutes=excluded.cooldown_minutes,notify_admins=excluded.notify_admins,updated_at=excluded.updated_at""", (alert_type,1 if enabled else 0,severity,threshold_ms,int(cooldown_minutes),1 if notify_admins else 0,now))\n    conn.commit()\n\n'''
if 'def ensure_alert_policy_schema' not in s:
    s=s.replace(needle, insert+needle)
# make emit_alert use policy if present
old='''    ensure_schema(conn)\n    now = now_iso()\n    try:\n'''
new='''    ensure_alert_policy_schema(conn)\n    policy = conn.execute("SELECT enabled, severity, cooldown_minutes, notify_admins FROM observability_alert_policies WHERE alert_type=?", (alert_type,)).fetchone()\n    if policy and not int(policy[0]):\n        return None\n    if policy:\n        severity = str(policy[1] or severity)\n        notify = bool(int(policy[3]))\n    cooldown = int(policy[2]) if policy else 10\n    now = now_iso()\n    try:\n'''
s=s.replace(old,new,1)
s=s.replace("(datetime.now(timezone.utc) - timedelta(minutes=10)).isoformat()", "(datetime.now(timezone.utc) - timedelta(minutes=cooldown)).isoformat()",1)
p.write_text(s)

# admin routes for both: guardian detectors/events and observability policies
p=root/'blueprints/admin.py'; s=p.read_text()
anchor='@admin_bp.route("/observability")\n'
insert='''@admin_bp.route("/guardian/detectors")\n@login_required\n@requires_permission("audit.view")\ndef admin_guardian_detectors():\n    from governance_service import guardian_detectors\n    conn=db.get_db(); rows=guardian_detectors(conn); conn.close()\n    return render_template("admin/guardian_detectors.html", detectors=rows)\n\n@admin_bp.route("/guardian/exception/<int:exception_id>/timeline")\n@login_required\n@requires_permission("audit.view")\ndef admin_guardian_exception_timeline(exception_id):\n    from governance_service import exception_timeline\n    conn=db.get_db(); rows=exception_timeline(conn, exception_id); conn.close()\n    return jsonify({"exception_id": exception_id, "events": [dict(r) for r in rows]})\n\n'''
if 'def admin_guardian_detectors' not in s:
    s=s.replace(anchor,insert+anchor)
anchor2='@admin_bp.route("/observability")\n'
insert2='''@admin_bp.route("/observability/policies", methods=["GET", "POST"])\n@login_required\n@requires_permission("settings.manage")\ndef admin_observability_policies():\n    import observability_service\n    conn=db.get_db()\n    if request.method == "POST":\n        check_csrf()\n        observability_service.set_alert_policy(conn, alert_type=request.form.get("alert_type", ""), enabled=request.form.get("enabled") == "1", severity=request.form.get("severity", "medium"), threshold_ms=request.form.get("threshold_ms", type=int), cooldown_minutes=request.form.get("cooldown_minutes", 10, type=int), notify_admins=request.form.get("notify_admins") == "1")\n        flash("Alert policy updated.", "success"); conn.close(); return redirect(url_for("admin.admin_observability_policies"))\n    rows=observability_service.alert_policies(conn); conn.close()\n    return render_template("admin/observability_policies.html", policies=rows)\n\n'''
if 'def admin_observability_policies' not in s:
    s=s.replace(anchor2,insert2+anchor2)
p.write_text(s)

# templates
(root/'templates/admin/guardian_detectors.html').write_text('''{% extends "admin/base.html" %}\n{% block title %}Guardian Detectors{% endblock %}\n{% block content %}<div class="admin-page-header"><div><p class="admin-eyebrow">Operations</p><h1>Guardian Detectors</h1><p>Known operational signals and their configured severity.</p></div></div><section class="card-box"><div class="table-wrap"><table class="admin-table"><thead><tr><th>Detector</th><th>Severity</th><th>Status</th><th>Description</th></tr></thead><tbody>{% for d in detectors %}<tr><td><strong>{{ d.title }}</strong><br><small>{{ d.code }}</small></td><td><span class="status-pill status-pill--{{ d.severity }}">{{ d.severity }}</span></td><td>{{ 'Enabled' if d.enabled else 'Disabled' }}</td><td>{{ d.description }}</td></tr>{% else %}<tr><td colspan="4">No detectors configured.</td></tr>{% endfor %}</tbody></table></div></section>{% endblock %}''')
(root/'templates/admin/observability_policies.html').write_text('''{% extends "admin/base.html" %}\n{% block title %}Alert Policies{% endblock %}\n{% block content %}<div class="admin-page-header"><div><p class="admin-eyebrow">System</p><h1>Alert Policies</h1><p>Control which operational signals create alerts and how aggressively they notify the team.</p></div></div><section class="card-box"><div class="table-wrap"><table class="admin-table"><thead><tr><th>Type</th><th>Enabled</th><th>Severity</th><th>Cooldown</th><th>Notify</th><th>Updated</th></tr></thead><tbody>{% for p in policies %}<tr><td>{{ p.alert_type }}</td><td>{{ 'Yes' if p.enabled else 'No' }}</td><td>{{ p.severity }}</td><td>{{ p.cooldown_minutes }} min</td><td>{{ 'Yes' if p.notify_admins else 'No' }}</td><td>{{ p.updated_at }}</td></tr>{% else %}<tr><td colspan="6">No custom alert policies yet. Defaults remain active.</td></tr>{% endfor %}</tbody></table></div><form method="POST" style="margin-top:1rem"><input type="hidden" name="csrf_token" value="{{ csrf_token() }}"><input class="admin-input" name="alert_type" required placeholder="Alert type"><select class="admin-input" name="severity"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select><input class="admin-input" name="threshold_ms" type="number" min="0" placeholder="Threshold ms (optional)"><input class="admin-input" name="cooldown_minutes" type="number" min="1" value="10"><label><input type="checkbox" name="enabled" value="1" checked> Enabled</label><label><input type="checkbox" name="notify_admins" value="1" checked> Notify admins</label><button class="admin-btn admin-btn--primary" type="submit">Save policy</button></form></section>{% endblock %}''')

# add nav links
p=root/'templates/admin/base.html'; s=p.read_text()
needle='{{ url_for(\'admin.admin_guardian\') }}'
# add after guardian line once
if 'admin_guardian_detectors' not in s:
    s=s.replace('<a href="{{ url_for(\'admin.admin_guardian\') }}" class="{{ \'active\' if admin_nav_active(\'guardian\') }}" onclick="closeAdminMenu()">{{ icon("shield") }} Guardian</a>', '<a href="{{ url_for(\'admin.admin_guardian\') }}" class="{{ \'active\' if admin_nav_active(\'guardian\') }}" onclick="closeAdminMenu()">{{ icon("shield") }} Guardian</a>\n      <a href="{{ url_for(\'admin.admin_guardian_detectors\') }}" class="{{ \'active\' if admin_nav_active(\'guardian\') }}" onclick="closeAdminMenu()">{{ icon("settings") }} Detectors</a>')
if 'admin_observability_policies' not in s:
    s=s.replace('<a href="{{ url_for(\'admin.admin_observability\') }}"', '<a href="{{ url_for(\'admin.admin_observability_policies\') }}" class="{{ \'active\' if admin_nav_active(\'observability\') }}" onclick="closeAdminMenu()">{{ icon("settings") }} Alert policies</a>\n      <a href="{{ url_for(\'admin.admin_observability\') }}"',1)
p.write_text(s)

# checks
(root/'scripts/test_round32_pd.py').write_text('''import sqlite3\nfrom pathlib import Path\nroot=Path(__file__).resolve().parents[1]\nimport sys\nsys.path.insert(0,str(root))\nfrom governance_service import ensure_guardian_mastery_schema, add_exception, record_exception_event, exception_timeline, guardian_detectors\nconn=sqlite3.connect(':memory:'); conn.row_factory=sqlite3.Row\nconn.executescript("CREATE TABLE admin_users(id INTEGER PRIMARY KEY, username TEXT, is_active INTEGER DEFAULT 1); CREATE TABLE business_exceptions(id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT, severity TEXT, title TEXT, description TEXT, entity TEXT DEFAULT '', entity_id INTEGER DEFAULT 0, metadata_json TEXT DEFAULT '{}', status TEXT DEFAULT 'open', resolved_by INTEGER, resolution TEXT DEFAULT '', created_at TEXT, resolved_at TEXT, assigned_to INTEGER, due_at TEXT, escalated_at TEXT, escalation_reason TEXT DEFAULT '', updated_at TEXT);")\nensure_guardian_mastery_schema(conn); eid=add_exception(conn,code='x',severity='high',title='X',description='x'); record_exception_event(conn,eid,'created',details={'source':'test'}); assert len(exception_timeline(conn,eid))==1; assert len(guardian_detectors(conn))>=3\nfrom observability_service import ensure_alert_policy_schema,set_alert_policy,alert_policies\nensure_alert_policy_schema(conn); set_alert_policy(conn,alert_type='test',enabled=True,severity='high',cooldown_minutes=7,notify_admins=True); assert any(r['alert_type']=='test' for r in alert_policies(conn))\nprint('Round 32 PD checks: PASS')\n''')
